# Script to run cluster commands on the Master Node to add worker nodes to cluster

---
# This enables the cluster on the Master Node 
- name: Cluster Setup Part 1
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" --header "Content-Type:application/json" --data "{\"action\":\"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\":\"{{couchdb_user}}\", \"password\":\"{{couchdb_pass}}\", \"port\":\"5984\", \"node_count\":\"{{node_count}}\", \"remote_node\":\"{{ item }}\", \"remote_current_user\":\"{{couchdb_user}}\", \"remote_current_password\":\"{{couchdb_pass}}\"}"
  loop: "{{ groups['workerservers'] }}"
  when: item != "{{ groups['workerservers'][0] }}"

# This Adds the corresponding worker nodes to the cluster
- name: Cluster Setup Part 2 
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" --header "Content-Type:application/json" --data "{\"action\":\"add_node\", \"host\":\"{{ item }}\", \"port\":\"5984\", \"username\":\"{{couchdb_user}}\", \"password\":\"{{couchdb_pass}}\"}"
  loop: "{{ groups['workerservers'] }}"
  when: item != "{{ groups['workerservers'][0] }}"

# Let Master Node know that the nodes have been added
- name: Finish Cluster Setup
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" \--header "Content-Type:application/json" --data "{\"action\":\"finish_cluster\"}" 

# Create empty AURIN databases on cluster
- name: Create AURIN Database
  command: curl -X PUT http://{{couchdb_user}}:{{couchdb_pass}}@{{ansible_default_ipv4.address}}:5984/{{item}}
  loop:
    - crime_rate
    - domestic_violence
    - personal_income
    - adult_health

# Replicate Existing AURIN data from existing database into this new cluster database
- name: Replicating AURIN data from our existing database
  command: curl -X POST http://{{couchdb_user}}:{{couchdb_pass}}@{{existing_database}}:5984/_replicator -d '{"source":"http://{{couchdb_user}}:{{couchdb_pass}}@{{existing_database}}:5984/{{item}}", "target":"http://{{couchdb_user}}:{{couchdb_pass}}@{{ansible_default_ipv4.address}}:5984/{{item}}"}' -H "Content-Type:application/json"
  loop:
    - crime_rate
    - domestic_violence
    - personal_income
    - adult_health







