# Tasks here create volumes that are defined in variables/instancedetails.yaml
# (Referred from Alwyn's Demo Code from Lecture)
---
# Create a volume from volumes list in variavbles/instancedetails.yaml
- name: Create volume(s) on NecTAR
  os_volume: 
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}' 
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# Put created volumes into a list
- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

# Print out created volumes
- name: Printing Created Volumes
  debug:
    msg: "Volume {{ os_vol_ids }} has been created."