# These tasks handle instance creation on Nectar using parameters from variables/instancedetails.yaml
# (Referred from Alwyn's Code on Demo from Lectures)
---

- name: Printing out our to be created instances
  debug:
    msg: 'Creating: {{ item }}'
  loop: '{{ instance_list }}'

# Creating our instances on Nectar using the os_server module
- name: Create all instances
  os_server:
    name: '{{ item.instance_name }}'
    image: '{{ item.instance_image }}'
    key_name: '{{ ansible_key_name }}'
    flavor: '{{ item.instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    #volumes: '{{ volume_name }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  with_items: '{{ instance_list }}'
  register: 'instances'

# Inserting created instance's IP addressed into our inventory file
- name: Insert all created instances into workerservers variable in inventory file
  become: yes
  lineinfile: 
    path: inventory.ini
    line: "{{ item.openstack.public_v4 }} " 
    insertafter: '\[workerservers\]'
  loop: '{{ instances.results }}'  



